version: '3'
services:
  sync-s3:
    image: ghcr.io/ice-bergtech/docker-sync-with-s3:latest
    environment:
      ACCESS_KEY: 
      SECRET_KEY: 
      CRON_SCHEDULE: '*/0 12 * * *' # Schedule for cron job, for every 15 minutes it would be: `*/15 * * * *`
      SOURCE_PATH: /data # Source files to be synced, example: `/data`
      DESTINATION_PATH: s3://my-bucket/site-uploads # Destination of where to sync files to, example: `s3://my-bucket/site-uploads`
      BUCKET_LOCATION: # AWS Region for bucket, ex: `us-east-1`
      # LOGENTRIES_KEY: #(optional) If provided, the image will send command output to syslog with priority `user.info`.
      # S4SYNC_ARGS: # (optional) If provided, the arguments will be included in the `aws s3 sync` command. For example, setting `S4SYNC_ARGS=--delete` will cause files in the destination to be deleted if they no longer exist in the source.
    volumes:
      # - ":/data/default:ro"
      - "data_BACKUPS:/data/backups:ro"
  
volumes:
  data_BACKUPS:
